/* This is a regular expression for email and password validation. */
const regex = {
  EMAIL: /[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/,
  PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
};

/* This is a constant variable which is used to store all the messages which are used in the application. */
const message = {
  SUCCESS: "Successful",
  FAILED: "Failed",
  WRONG: "Something went wrong",
  INVALID_EMAIL: "Email is invalid",
  INVALID_PASSWORD: "Password is invalid",
  USER_FOUND: "User found",
  USER_NOT_EXISTS: "User does not exists",
  USER_EXISTS: "User exists with this email",
  USER_REGISTERATION: "User registered",
  VERIFICATION_CODE_SEND: "Email verification code sent",
  VERIFICATION_CODE_ALREADY_SEND: "Email verification code is already sent",
  VERIFICATION_CODE_RESEND: "Verification code resend",
  EMAIL_VERIFIED: "Email verified",
  EMAIL_ALREADY_VERIFIED: "Email already verified",
  EMAIL_VERIFICATION_FAILED: "Email verification failed",
  LOGIN: "Login user",
  LOGIN_EMAIL_SEND: "Recent login email send",
  WRONG_PASSWORD: "Password does not match",
  FORGET_PASSWORD: "Forget password link sent",
  FORGET_PASSWORD_LINK_ALREADY_SEND: "Forget password link send already",
  FORGET_PASSWORD_LINK_RESEND: "Send forget password link again",
  FORGET_PASSWORD_FAILED: "Forget password link send failed",
  FORGET_PASSWORD_CODE_MISMATCH: "Forget password code does not match",
  PASSWORD_CHANGED: "Password changed",
  PASSWORD_CHANGED_FAILED: "Password change failed",
  PASSWORD_NOT_MATCHED: "Password and confirm password should match",
  UNAUTHENTICATED:"Unauthenticated user",
  OLD_PASSWORD_MISMATCH: "Old password and new password does not matched",
  USER_PROFILE: "User profile retrived",
  USER_PROFILE_UPDATE_FAILED: "User profile update failed",
  USER_PROFILE_UPDATE: "User profile updated",
  USERS: "Get all users",
  PROFILE_PHOTO_UPLOAD_FAILED: "Profile photo upload failed",
  PROFILE_PHOTO_UPLOAD: "Profile photo uploaded",
  PROFILE_PHOTO_SIZE: "File size should not more than 1 MB"
};

/* This is a constant variable which is used to store all the status code which are used in the application. */
const statusCode = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  PROCESSING: 102,
  EARLY_HINTS: 103,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTI_STATUS: 207,
  ALREADY_REPORTED: 208,
  IM_USED_: 226,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  SWITCH_PROXY: 306,
  TEMPORARY_REDIRECT: 307,
  PERMANENT_REDIRECT: 308,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  PAYLOAD_TOO_LARGE: 413,
  URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  IM_A_TEAPOT: 418,
  MISDIRECTED_REQUEST: 421,
  UNPROCESSABLE_ENTITY: 422,
  LOCKED: 423,
  FAILED_DEPENDENCY: 424,
  TOO_EARLY: 425,
  UPGRADE_REQUIRED: 426,
  PRECONDITION_REQUIRED: 428,
  TOO_MANY_REQUESTS: 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE: 431,
  UNAVAILABLE_FOR_LEGAL_REASONS: 451,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505,
  VARIANT_ALSO_NEGOTIATES: 506,
  INSUFFICIENT_STORAGE: 507,
  LOOP_DETECTED: 508,
  NOT_EXTENDED: 510,
  NETWORK_AUTHENTICATION_REQUIRED: 511
};

module.exports = {
  regex, 
  message, 
  statusCode,
};